#!/bin/bash
############################# Функции ################################
create_header()
{
echo "<?xml version='1.0' encoding='UTF-8'?>
<!-- Командный файл для обработки osm-файла с помощью утилиты osmpatch -->
<osmpatch>"
}

create_end()
{
echo "</osmpatch>"
}


create_patchset()
{
echo "<patchset>
	<find>
		<type nodes='yes' ways='yes' relation='yes'/>
		<tag>
			<key full_match='yes'>power</key>
			<value full_match='yes'>station</value>
		</tag>
		<tag>
			<key full_match='yes'>name</key>
			<value full_match='yes' case_sensitive='yes'>$1</value>
		</tag>
	</find>
	<add>
		<tag k='power_usage_percent' v='$2' />
		<tag k='power_usage_comment' v='$3' />
		<tag k='power_usage_set_date' v='$4' />
	</add>
</patchset>"
}
######################################################################


# Основной скрипт
if [ -z "${1}" ]
then
	echo "Необходимо указать входной файл c загрузкой по мощности подстанций, где в первой строке есть описание, с 5-й строки начинаются данные,
во втором столбце - название станции, в 20-м столбце - процент загрузки."
	echo "Пример:"
	echo "$0 \"КДЗ Август з загрузкой трансформаторов.xls\""
	exit 1
fi

create_header


in1="$1"
comment="дата съёма неопределена"
line=0
xls2csv -c';' "${in1}" 2>/dev/null |while read text1
do
	line=`expr $line + 1`

	if [ 1 -eq ${line} ]
	then
		# Берём описание:
		comment="`echo ${text1}|awk '{print $1}' FS=';'|sed 's/"//g'|sed 's/.*на территории Приморского края на/Показания на/'`"
	fi

	if [ 5 -gt ${line} ]
	then
		# Пропускаем заголовок
		continue
	fi
	#echo "text1=$text1"
	name="`echo ${text1}|awk '{print $2}' FS=';'|sed 's/"//g'`"
	power="`echo ${text1}|awk '{print $20}' FS=';'|sed 's/"//g'`"
	set_date="`date +%d.%m.%Y`"

	if [[ "В С Е Г О" == "${name}" ]]
	then
		continue
	fi
	#echo "name=${name}, power=${power} comment=$comment"
	create_patchset "${name}" "${power}" "${comment}" "${set_date}"
done

create_end

exit 0

